### ISSUE TITLE
Command line editing doesn't seem to be working

### ISSUE THREAD

**Issue by hms** [steakknife/spirit_hands#16] opened 2016-11-21 02:07 UTC
Steps to reproduce:
-3. Add spirit_hands gem to dev and test group
  -3a.  Remove all gem lines that are included as part of the spirit_hands dependencies
-2. bundle install
  -2a. Run rails console to verify SpiritHands is installed.  Proof includes:
  Prompt includes all of the expected changes.  Prompt shows the double >> suggesting readline
  Binding.pry works as expected despite the pry gem not being explicitly in the Gemfile
-1. Attempt to invoke vim editing with escape key.  Type any vim edit commands and have them be added to the line as code.
0. MacOS -- latest with all updates
1. Standard MacOS terminal program
2. TERM=xterm-256color
3. Ruby 2.3.1p112
  3a. Rails-5.0.0.1
4. Ruby was installed via RVM install ruby-2.3
5. Ruby was compiled with Readline edit.  This is verified by using irb without SpiritHands and editing works.  Second verification is to remove the SpiritHands gem and editing becomes available again
6. Ruby is NOT being run as root

**Comment by steakknife** [comment] 2016-11-22 05:45
1. What does the output of `rails console` look like?
2. Can you upload a Minimal Example to github? (For reproducibility)

**Comment by steakknife** [comment] 2016-11-22 08:47
Preliminary investigation reveals some issues in coolline.

**Comment by steakknife** [comment] 2016-11-22 08:54
If it's resolved by the following, then it's `pry-coolline`.

```ruby
Pry.input = Readline
Pry.config.completer = Pry::InputCompleter.new
```

I'm WIP on coollline enable/disable and fixing integration off of issue #17

**Comment by hms** [comment] 2016-11-22 16:19
First, thanks for all of the help and amazing responsiveness!

Second, the above Pry stuff did fix the problem (Pry.input = Readline; Pry.config.completer = ...)

Per a previous conversation:
I'm pretty sure stock Rails 5 defaults to using the rails shell from a bundle --binstubs.  I've checked my environment and I'm not doing anything funny in my environment or my tool chain and I'm defaulting to bin/rails.

**Comment by hms** [comment] 2016-11-22 16:25
A quick follow up. It seems that all that is really needed is the Pry.input = Readline.  I've tested with and without the Pry.config.completer line.  It doesn't seem to help or hurt.

**Comment by steakknife** [comment] 2016-11-23 01:58
pry-coolline is disabled by default in 2.1.2 until a better fork of pry-coolline can be provided.

It can be re-enabled with a new option in .pryrc, but I wouldn't recommend doing it until the underlying coolline is fixed. coolline takes the place of readline in `Pry.input` but does so by partially incomplete emulation of readline behavior (because it live syntax colorizes).

`SpiritHands.coolline = true`

**Comment by steakknife** [comment] 2016-11-23 01:58
Please let me know if this works better for you.

**Comment by hms** [comment] 2016-11-23 05:07
There is a typo in lib/spirit_hands.rb:20.
You have: 
  Pry.plugin['rails'].activate! 
and it need to be
  Pry.plugins['rails'].activate! # plugin needs to be plural

**Comment by steakknife** [comment] 2016-11-23 12:25
Ah thanks.

**Comment by steakknife** [comment] 2016-11-23 12:31
Yanked 2.1.2 and pushed 2.1.3

**Comment by steakknife** [comment] 2016-11-25 22:25
Should be usable now. If not, please follow-up.

**Closed by steakknife** 2016-11-25 22:25 UTC
Labels: bug, needs feedback
